site_name: 'PASTa'
nav:
  - Home: index.md 
  - Getting Started: gettingstarted.md
  - User Guide: 
    - User Guide: userguide/userguide.md
    - Data Preparation: userguide/datapreparation.md
    - Signal Processing: userguide/signalprocessing.md
    - Transient Analysis: userguide/transientanalysis.md
  - Example Analyses: exampleanalyses.md
  - Function Documentation: functiondocumentation.md
  - About: 
    - PASTa Team: about/pastateam.md
    - Version Release Notes: about/releasenotes.md
    - How to Cite PASTa: about/citepasta.md
    - License: about/license.md
    - Contact Us: contactus.md
    - References: about/references.md
  - Resources: learningresources.md

theme:
  name: mkdocs
  features:
    - navigation.footer
